import React from 'react';
import { motion } from "framer-motion";

const Page3 = () => {
  const textVariant = {
    hidden: { opacity: 0, x: -100 },
    visible: {
        opacity: 1,
        x: 0,
        transition: {
            duration: 0.8,
            ease: "easeInOut",
        },
    },
  };
  return (
    <div className="flex flex-col items-center justify-start h-auto px-6 text-center bg-gradient-to-r from-green-200 to-blue-300 py-10">
      <h1 className="w-3/4 py-10 text-4xl md:text-5xl lg:text-6xl font-bold text-gray-800 mb-4">
      The True Cost of Fuel: How Transportation Impacts Our Environment
      </h1>
      <div className="max-w-3xl mx-auto">
        <motion.p
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
         className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 mb-6 text-justify">
          Transportation plays a vital role in modern society, enabling the movement of people, goods, and services. However, its environmental impact is a pressing issue that cannot be overlooked. The most significant ways in which transportation harms the environment are through air pollution, resource depletion, and waste generation.
        </motion.p>
        <motion.p
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
         className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 mb-6 text-justify">
          One of the primary pollutants from transportation is carbon dioxide (CO2), a greenhouse gas that contributes to climate change. Nitrogen oxides (NOx) and fine particulate matter, emitted by motorized vehicles, not only degrade air quality but also pose serious health risks, particularly in densely populated urban areas. As more vehicles take to the roads, the environmental burden of air pollution grows, exacerbating global warming and health disparities.
        </motion.p>
        <motion.p
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
        className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 mb-6 text-justify">
          Moreover, the transportation sector's reliance on fossil fuels further compounds its negative environmental impact. The extraction, refinement, and distribution of these fuels are resource-intensive processes that lead to the depletion of non-renewable resources and the release of more harmful greenhouse gases into the atmosphere. The constant demand for gasoline and diesel fuels results in rising pollution levels and the acceleration of climate chang
        </motion.p>
        <motion.p 
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
        className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 text-justify">
          In addition to pollution, the transport sector generates a significant amount of waste, including discarded tires, used oils, and vehicles that have reached the end of their useful lives. If these materials are not managed properly, they can leach into the soil and water, causing further environmental degradation. The waste generated by the transport sector poses long-term challenges for waste management systems and ecosystems alike.

        </motion.p>
        <br />
        <motion.p 
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
        className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 text-justify">
          To mitigate these environmental impacts, the promotion of sustainable transportation options is crucial. Electric vehicles (EVs), for instance, offer a cleaner alternative by producing fewer emissions and reducing reliance on fossil fuels. Public transportation systems, when properly developed and maintained, can significantly decrease the number of individual vehicles on the road, leading to lower emissions and reduced traffic congestion. Furthermore, promoting infrastructure for cycling and walking not only reduces the need for motorized vehicles but also improves public health by encouraging active transportation.
        </motion.p>
        <br />
        <motion.p 
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
        className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 text-justify">
          In addition to adopting these alternative modes of transport, research and innovation in cleaner technologies are essential. Developing and implementing more energy-efficient vehicles, alternative fuels, and emission-reduction technologies can drive meaningful change. Policymakers must also prioritize legislation that supports emission reductions, incentivizes sustainable practices, and promotes investment in eco-friendly infrastructure.
        </motion.p>
        <br />  
        <motion.p 
        initial="hidden"
        whileInView="visible"
        viewport={{ amount: 0.5 }}
        variants={textVariant}
        className="text-base leading-relaxed text-lg md:text-xl lg:text-2xl text-gray-700 text-justify">
          To sum up, while transportation remains a cornerstone of modern society, it is clear that its environmental impact must be addressed. By embracing sustainable transport options and advancing cleaner technologies, we can reduce pollution, conserve resources, and pave the way for a greener, more sustainable future.
        </motion.p>
      </div>
    </div>
  );
};

export default Page3
